### ISSUE TITLE
Error in pterosync.php

### ISSUE THREAD

**Issue by adamikhlef** [wohahobg/pterosync#40]
```
ParseError: syntax error, unexpected '=>' (T_DOUBLE_ARROW) in /home/northaf2/public_html/modules/servers/pterosync/pterosync.php:969
Stack trace:
#0 /home/northaf2/public_html/vendor/whmcs/whmcs-foundation/lib/Module/Server.php(0): WHMCS\Module\AbstractModule->load('pterosync')
#1 /home/northaf2/public_html/admin/configproducts.php(0): WHMCS\Module\Server->getListWithDisplayNames()
#2 {main}
```

**Comment by wohahobg** [comment]
![image](https://github.com/user-attachments/assets/183c6d46-8460-42bc-bee2-ca106595e22b)
